---
- hosts: localhost
  tasks:
  - name: remove ingress
    kubernetes.core.k8s:
      state: absent
      src: ingress.yaml
  - name: Remove ngrok release and waiting suppression ending
    kubernetes.core.helm:
      name: ngrok-operator
      release_namespace: ngrok-ingress-controller
      state: absent
      wait: true
  - name: "remove kubernetes python package"
    pip:
      name: kubernetes
      state: absent