---
- hosts: localhost
  tasks:
  - name: "Install kubernetes python package"
    pip:
      name: kubernetes
      state: present
  - name: Add ngrok chart repo
    kubernetes.core.helm_repository:
      name: ngrok
      repo_url: "https://charts.ngrok.com"
  - name: Deploy latest version of ngrok
    kubernetes.core.helm:
      name: ngrok-operator
      chart_ref: ngrok/ngrok-operator
      release_namespace: ngrok-ingress-controller
      create_namespace: true
      set_values:
        - value: credentials.apiKey="{{ lookup('ansible.builtin.env', 'NGROK_API_KEY') }}"
          value_type: string
        - value: credentials.authtoken="{{ lookup('ansible.builtin.env', 'NGROK_AUTHTOKEN') }}"
          value_type: string
  - name: install ingress
    kubernetes.core.k8s:
      state: present
      src: ingress.yaml
